[package]
name = "toml-editor"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml_edit = "0.14.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
